jobs:
  include:
    - stage: unit test
      os: linux
      dist: xenial
      language: go
      go: 1.13.x
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
          - $HOME/.cargo
          - CasperLabs
      script:
        - make test
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: unit test
      os: osx
      osx_image: xcode11.3
      language: go
      go: 1.13.x
      cache:
        directories:
          - $HOME/Library/Caches/go-build
          - $HOME/gopath/pkg/mod
          - $HOME/.cargo
          - CasperLabs
      script:
        - unset -f cd # workaround for https://github.com/travis-ci/travis-ci/issues/8703
        - make test

addons:
  apt:
    packages: curl
  homebrew:
    package: curl
before_install:
  - bash scripts/travis_ci_prerequisites.sh
  - export PATH="$PATH:$HOME/.cargo/bin"
  - export PATH="$PATH:$HOME/protoc/bin"
install:
  - make install
before_script:
  - ./CasperLabs/execution-engine/target/release/casperlabs-engine-grpc-server $HOME/.casperlabs/.casper-node.sock& # for integration test.
