# CasperLabs Execution Engine Chainspec
[genesis]
# Timestamp for the genesis block, also used in seeding the pseudo-random number
# generator used in execution engine for computing genesis post-state.
timestamp = 0

# semver.
protocol-version = "1.0.0"

# Path (absolute, or relative to the manifest) to the file containing wasm bytecode for installing the mint system contract.
mint-code-path = "../contracts/mint_install.wasm"

# Path (absolute, or relative to the manifest) to the file containing wasm bytecode for installing the PoS system contract.
pos-code-path = "../contracts/pos_install.wasm"

[wasm-costs]
# Default opcode cost
regular = 1
# Div operations multiplier.
div-multiplier = 16
# Mul operations multiplier.
mul-multiplier = 4
# Memory (load/store) operations multiplier.
mem-multiplier = 2
# Amount of free memory (in 64kb pages) each contract can use for stack.
mem-initial-pages = 4096
# Grow memory cost, per page (64kb)
mem-grow-per-page = 8192
# Memory copy cost, per byte
mem-copy-per-byte = 1
# Max stack height (native WebAssembly stack limiter)
max-stack-height = 65536
# Cost of wasm opcode is calculated as TABLE_ENTRY_COST * `opcodes_mul` / `opcodes_div`
opcodes-multiplier = 3
opcodes-divisor = 8
